
services:
  app:
    build:
      context: ./app  # Dossier contenant l'application Flask avec MongoDB
    container_name: app
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    expose:
      - "5000"  # Port exposé uniquement au sein du réseau Docker
    networks:
      - app_network

  app2:
    build:
      context: ./app2  # Dossier contenant l'application Flask sans MongoDB
    container_name: app2
    expose:
      - "5000"
    networks:
      - app_network

  mongo:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - mongo_data:/data/mydatabase
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    ports:
      - "80:80"  # Expose NGINX to the host machine on port 80
    depends_on:
      - app
      - app2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
