namespace: alefevre

mongodb:
  image: mongo:latest
  port: 27017
  resources:
    requests:
      memory: "100Mi"  # Increase the memory request
      cpu: "100m"
    limits:
      memory: "200Mi"  # Increase the memory limit
      cpu: "200m"
  storage:
    size: "1Gi"
  storageClass: longhorn


webdb:
  image: pomelo971/app:v3
  replicas: 3
  port: 5000
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

webnodb:
  image: pomelo971/app2:v1
  port: 5000
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

ingress:
  hostnames:
    webnodb: webnodb.alefevre.net4255.luxbulb.org
    webdb: webdb.alefevre.net4255.luxbulb.org
