apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
